# Generated by Django 4.2.7 on 2023-12-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombre',
            name='precio',
            field=models.IntegerField(max_length=30),
        ),
    ]
