# Generated by Django 4.2.7 on 2023-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_disfraces_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='STock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDisfraces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=30)),
                ('talle', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='disfraces',
            old_name='disfraces',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='disfraces',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
    ]
